In [1]:
import pandas as pd
df = pd.read_csv("train.csv")

In [2]:
df.head()

,Distance Between Stations (km),Weather Conditions,Day of the Week,Time of Day,Train Type,Historical Delay (min),Route Congestion
0,100,Clear,Monday,Morning,Express,5,Low
1,150,Rainy,Tuesday,Afternoon,Superfast,10,Medium
2,200,Foggy,Wednesday,Evening,Local,15,High
3,50,Clear,Thursday,Night,Express,2,Low
4,75,Rainy,Friday,Morning,Superfast,8,Medium

In [3]:
df.describe()

       Distance Between Stations (km)  Historical Delay (min)
count                     2878.000000             2878.000000
mean                       184.423211               93.324878
std                        169.394783              195.923817
min                          0.000000                0.000000
25%                         70.000000               13.000000
50%                        155.000000               35.000000
75%                        225.000000               74.000000
max                        955.000000             1230.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2878 entries, 0 to 2877
Data columns (total 7 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Distance Between Stations (km)  2878 non-null   int64
 1   Weather Conditions              2878 non-null   object
 2   Day of the Week                 2878 non-null   object
 3   Time of Day                     2878 non-null   object
 4   Train Type                      2878 non-null   object
 5   Historical Delay (min)          2878 non-null   int64
 6   Route Congestion                2878 non-null   object
dtypes: int64(2), object(5)
memory usage: 157.5+ KB

In [5]:
df.shape

(2878, 7)

In [6]:
for col in df.select_dtypes(include='object').columns:
    print(col, df[col].nunique())
#this tells us how many unique values each categorical columns has

Weather Conditions 3
Day of the Week 7
Time of Day 4
Train Type 3
Route Congestion 3

In [7]:
dummies =pd.get_dummies(df,drop_first=True)

In [8]:
dummies.shape

(2878, 17)

In [9]:
X = dummies.drop('Historical Delay (min)',axis = 1)

In [10]:
y = dummies['Historical Delay (min)']

In [11]:
print(X.shape)
print(y.shape)

(2878, 16)
(2878,)

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [13]:
print(X_train.shape)

(2302, 16)

In [14]:
print(y_test.shape)

(576,)

In [15]:
from sklearn.ensemble import RandomForestRegressor
rf_model = RandomForestRegressor()

In [16]:
rf_model.fit(X_train,y_train)

RandomForestRegressor()

In [17]:
y_pred = rf_model.predict(X_test)

In [18]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
import numpy as np

rf_mae = mean_absolute_error(y_test,y_pred)
rmse = np.sqrt(mean_squared_error(y_test,y_pred))

print(rf_mae)
print(rmse)

31.1779085260804
54.674073632321594

In [19]:
train_pred = rf_model.predict(X_train)
train_mae = mean_absolute_error(y_train, train_pred)
print("Train mae:",train_mae)
print("test mae: ",rf_mae)

Train mae: 14.570110565561476
test mae:  31.1779085260804

In [20]:
rf_model2 =  RandomForestRegressor(n_estimators=200,max_depth=10,random_state=42)
rf_model2.fit(X_train, y_train)

train_pred2 = rf_model2.predict(X_train)
test_pred2 = rf_model2.predict(X_test)

print("Train mae:",mean_absolute_error(y_train, train_pred2))

print("test mae: ",mean_absolute_error(y_test, test_pred2))

Train mae: 23.00653635431748
test mae:  29.88507126979777

In [21]:
import pickle 
with open('model.pkl', 'wb') as f:
    pickle.dump(rf_model2, f)
    
print("Model saved Successfully")

Model saved Successfully

In [22]:
with open('model.pkl', 'rb') as f:
    loaded_model = pickle.load(f)
print(loaded_model)

RandomForestRegressor(max_depth=10, n_estimators=200, random_state=42)

In [23]:
import pickle

feature_columns = X.columns.tolist()
with open('feature_columns.pkl', 'wb') as f:
    pickle.dump(feature_columns, f)
    
print(feature_columns)

['Distance Between Stations (km)', 'Weather Conditions_Foggy', 'Weather Conditions_Rainy', 'Day of the Week_Monday', 'Day of the Week_Saturday', 'Day of the Week_Sunday', 'Day of the Week_Thursday', 'Day of the Week_Tuesday', 'Day of the Week_Wednesday', 'Time of Day_Evening', 'Time of Day_Morning', 'Time of Day_Night', 'Train Type_Local', 'Train Type_Superfast', 'Route Congestion_Low', 'Route Congestion_Medium']

In [24]:
type(feature_columns)

list

In [25]:
feature_columns[:5]

['Distance Between Stations (km)',
 'Weather Conditions_Foggy',
 'Weather Conditions_Rainy',
 'Day of the Week_Monday',
 'Day of the Week_Saturday']

In [26]:
{
  "distance": 150,
  "weather": "Sunny",
  "day_of_week": "Monday",
  "train_type": "Express",
  "route_congestion": "Low"
}

{'distance': 150,
 'weather': 'Sunny',
 'day_of_week': 'Monday',
 'train_type': 'Express',
 'route_congestion': 'Low'}

In [33]:
df['Day of the Week'].unique()

array(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday',
       'Sunday'], dtype=object)

In [29]:
df['Weather Conditions'].unique()

array(['Clear', 'Rainy', 'Foggy'], dtype=object)

In [30]:
df['Train Type'].unique()

array(['Express', 'Superfast', 'Local'], dtype=object)

In [31]:
df['Time of Day'].unique()

array(['Morning', 'Afternoon', 'Evening', 'Night'], dtype=object)

In [32]:
df['Route Congestion'].unique()

array(['Low', 'Medium', 'High'], dtype=object)